version: '3.8'

services:
  backend:
    image: ${REGISTRY_URL}/webapp-backend:${VERSION:-latest}
    container_name: webapp-backend
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
    ports:
      - "5000:5000"
    networks:
      - webapp-network
    restart: always

  frontend:
    image: ${REGISTRY_URL}/webapp-frontend:${VERSION:-latest}
    container_name: webapp-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - webapp-network
    restart: always

networks:
  webapp-network:
    driver: bridge